---

.build:
  image: node:lts
  script:
    - |
      echo "Creating .env file for the build process"
      echo "BASE_API_URL='http://localhost'" > .env
      echo "NEXT_PUBLIC_SENTRY_DSN=''" >> .env
      echo "NEXT_PUBLIC_SENTRY_ENVIRONMENT=staging" >> .env
      echo "SENTRY_AUTH_TOKEN=''" >> .env

    - echo "Installing dependencies"
    - yarn install

    - echo "Building the project"
    - yarn run build
