stages:
    - lint

variables:
    NODE_ENV: production

before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    - yarn install

lint_job:
    image: node:20
    stage: lint
    script:
        - yarn run build
        - |
            if ! yarn run lint; then
              echo "Linting failed, but continuing..."
            fi
        - |
            if ! yarn run lint:types; then
              echo "TypeScript linting failed, but continuing..."
            fi
        - |
            if ! npm run lint:scss; then
              echo "SCSS linting failed, but continuing..."
            fi
    only:
        - master
    except:
        - tags
        - triggers

merge_requests:
    image: node:20
    stage: lint
    script:
        - yarn run build
        - |
            if ! yarn run lint; then
              echo "Linting failed, but continuing..."
            fi
        - |
            if ! yarn run lint:types; then
              echo "TypeScript linting failed, but continuing..."
            fi
        - |
            if ! npm run lint:scss; then
              echo "SCSS linting failed, but continuing..."
            fi
    only:
        - merge_requests
    except:
        - tags
        - triggers
