---

include:
  - local: /.gitlab/job/build.yml
  - local: /.gitlab/job/check.yml

stages:
  - check
  - build

build:
  stage: build
  extends:
    - .build

check-lint:
  stage: check
  extends:
    - .check-lint
