/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Summit-X
 * Summit-X is the project about mountains and mountaineers
 * OpenAPI spec version: 0.1.0
 */
import { createInstance } from './api-instanse';
export type UserListParams = {
    /**
     * JSON-encoded array of requested range. Example: [0, 9]
     */
    range?: string;
    /**
     * JSON-encoded array which specifies results ordering. First value is order field and the second is direction. Example: ["id", "ASC"]
     */
    sort?: string;
    /**
     * Quick filter string. Not all backend endpoints are able to process it
     */
    q?: string;
};

export type MountainRangeParams = {
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type MountainRangesListParams = {
    /**
     * JSON-encoded array of requested range. Example: [0, 9]
     */
    range?: string;
    /**
     * JSON-encoded array which specifies results ordering. First value is order field and the second is direction. Example: ["id", "ASC"]
     */
    sort?: string;
    /**
     * Quick filter string. Not all backend endpoints are able to process it
     */
    q?: string;
    /**
     * Filters to apply. JSON object of type **GeodataMountainRangeListFilter**
     */
    filter: ReactAdminJsonQueryParamJSONValue;
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type MountainPassParams = {
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type MountainPassesListParams = {
    /**
     * JSON-encoded array of requested range. Example: [0, 9]
     */
    range?: string;
    /**
     * JSON-encoded array which specifies results ordering. First value is order field and the second is direction. Example: ["id", "ASC"]
     */
    sort?: string;
    /**
     * Quick filter string. Not all backend endpoints are able to process it
     */
    q?: string;
    /**
     * Filters to apply. JSON object of type **GeodataMountainPassListFilter**
     */
    filter: ReactAdminJsonQueryParamJSONValue;
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type MountainParams = {
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type MountainsListParams = {
    /**
     * JSON-encoded array of requested range. Example: [0, 9]
     */
    range?: string;
    /**
     * JSON-encoded array which specifies results ordering. First value is order field and the second is direction. Example: ["id", "ASC"]
     */
    sort?: string;
    /**
     * Quick filter string. Not all backend endpoints are able to process it
     */
    q?: string;
    /**
     * Filters to apply. JSON object of type **GeodataMountainListFilter**
     */
    filter: ReactAdminJsonQueryParamJSONValue;
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type GlacierParams = {
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type GlaciersListParams = {
    /**
     * JSON-encoded array of requested range. Example: [0, 9]
     */
    range?: string;
    /**
     * JSON-encoded array which specifies results ordering. First value is order field and the second is direction. Example: ["id", "ASC"]
     */
    sort?: string;
    /**
     * Quick filter string. Not all backend endpoints are able to process it
     */
    q?: string;
    /**
     * Filters to apply. JSON object of type **GeodataGlacierListFilter**
     */
    filter: ReactAdminJsonQueryParamJSONValue;
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type CountryRegionParams = {
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type CountryParams = {
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

/**
 * This value should be kept in secret. On the server side, it will be hidden from logs
 */
export type WebappCoreSecstrSecUtf8 = string;

/**
 * JSON-encoded object
 */
export type ReactAdminJsonQueryParamJSONValue = string;

export type CountryRegionsListParams = {
    /**
     * JSON-encoded array of requested range. Example: [0, 9]
     */
    range?: string;
    /**
     * JSON-encoded array which specifies results ordering. First value is order field and the second is direction. Example: ["id", "ASC"]
     */
    sort?: string;
    /**
     * Quick filter string. Not all backend endpoints are able to process it
     */
    q?: string;
    /**
     * Filters to apply. JSON object of type **GeodataCountryRegionListFilter**
     */
    filter: ReactAdminJsonQueryParamJSONValue;
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

export type CountriesListParams = {
    /**
     * JSON-encoded array of requested range. Example: [0, 9]
     */
    range?: string;
    /**
     * JSON-encoded array which specifies results ordering. First value is order field and the second is direction. Example: ["id", "ASC"]
     */
    sort?: string;
    /**
     * Quick filter string. Not all backend endpoints are able to process it
     */
    q?: string;
    /**
     * Filters to apply. JSON object of type **GeodataCountryListFilter**
     */
    filter: ReactAdminJsonQueryParamJSONValue;
    /**
     * Language in ISO 639-2 format
     */
    locale_lang?: LocaleApiIsolangLanguage;
    /**
     * Metric system to use
     */
    metric_system?: LocaleMetricSystem;
};

/**
 * Empty response object on success
 */
export interface ReactAdminOKResponse {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    [key: string]: any;
}

/**
 * Length with information about it's unit
 */
export interface LocaleApiQuantitiesLengthQuantity {
    /** Amount of the length */
    amount: number;
    /** Unit of measure: Meter, Kilometer, Foot, Mile */
    unit: string;
}

/**
 * Area size with information about it's unit
 */
export interface LocaleApiQuantitiesAreaQuantity {
    /** Amount of the area size */
    amount: number;
    /** Unit of measure Square_Meter, Square_Kilometer, Square_Foot, Square_Mile */
    unit: string;
}

/**
 * String with information about it's language
 */
export interface LocaleApiLocaleLocalizedString {
    /** 3-letter language code, according to ISO 639-2 */
    lang: string;
    /** String value */
    value: string;
}

/**
 * Localized name
 */
export type LocaleApiLocaleGeoNameValueAnyOfTwo = {
    LocalString?: LocaleApiLocaleLocalizedString;
};

/**
 * Name without knowledge about it's localization
 */
export type LocaleApiLocaleGeoNameValueAnyOf = {
    /** Unlocalized name */
    String?: string;
};

export type LocaleApiLocaleGeoNameValue =
    | LocaleApiLocaleGeoNameValueAnyOf
    | LocaleApiLocaleGeoNameValueAnyOfTwo;

/**
 * Kind of the name
 */
export type LocaleApiLocaleGeoNameKind =
    (typeof LocaleApiLocaleGeoNameKind)[keyof typeof LocaleApiLocaleGeoNameKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocaleApiLocaleGeoNameKind = {
    Main: 'Main',
    Old: 'Old',
    Alt: 'Alt',
    International: 'International',
    Local: 'Local',
    National: 'National',
    Official: 'Official',
} as const;

/**
 * Name of geographical object
 */
export interface LocaleApiLocaleGeoName {
    /** Kind of the name */
    kind: LocaleApiLocaleGeoNameKind;
    value: LocaleApiLocaleGeoNameValue;
}

/**
 * Language code according to ISO 639-2
 */
export type LocaleApiIsolangLanguage = string;

/**
 * @nullable
 */
export type GeodataDbSourcePropertiesVolcanoVolcanoType = VolcanoType | null;

/**
 * @nullable
 */
export type GeodataDbSourcePropertiesVolcanoStatus = VolcanoStatus | null;

export interface GeodataDbSourcePropertiesVolcano {
    /** @nullable */
    status?: GeodataDbSourcePropertiesVolcanoStatus;
    /** @nullable */
    volcano_type?: GeodataDbSourcePropertiesVolcanoVolcanoType;
}

export type VolcanoType = (typeof VolcanoType)[keyof typeof VolcanoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VolcanoType = {
    Stratovolcano: 'Stratovolcano',
    Shield: 'Shield',
    Scoria: 'Scoria',
} as const;

export type VolcanoStatus = (typeof VolcanoStatus)[keyof typeof VolcanoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VolcanoStatus = {
    Active: 'Active',
    Dormant: 'Dormant',
    Extinct: 'Extinct',
} as const;

/**
 * Element of user list
 */
export interface UserListResponse {
    /** When user was created */
    create_date: string;
    /** Internal user ID */
    id: number;
    /**
     * When authenticated user used API last time
     * @nullable
     */
    last_seen_date?: string | null;
    /** Total number of times user ever logged in */
    login_count: number;
    /** User person */
    person: string;
    /** Username */
    username: string;
}

/**
 * Element of user list
 */
export interface UserInfoResponse {
    /** Active user sessions count */
    active_sessions: number;
    /** When user was created */
    create_date: string;
    /** Internal user ID */
    id: number;
    /**
     * When authenticated user used API last time
     * @nullable
     */
    last_seen_date?: string | null;
    /** Total number of times user ever logged in */
    login_count: number;
    /** User person */
    person: string;
    /** Username */
    username: string;
}

/**
 * Order direction for paginated list output
 */
export type OrderDirection = (typeof OrderDirection)[keyof typeof OrderDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderDirection = {
    ASC: 'ASC',
    DESC: 'DESC',
} as const;

/**
 * Metric system to use in the response
 */
export type LocaleMetricSystem = (typeof LocaleMetricSystem)[keyof typeof LocaleMetricSystem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocaleMetricSystem = {
    Metric: 'Metric',
    Imperial: 'Imperial',
} as const;

/**
 * Which language and metric system to use in the response
 */
export interface LocaleRequest {
    /** Language in ISO 639-2 format */
    locale_lang?: string;
    metric_system?: LocaleMetricSystem;
}

/**
 * @nullable
 */
export type GeodataMountainResponseVolcano = GeodataDbSourcePropertiesVolcano | null;

/**
 * @nullable
 */
export type GeodataMountainResponseProminence = LocaleApiQuantitiesLengthQuantity | null;

/**
 * @nullable
 */
export type GeodataMountainResponseElevation = LocaleApiQuantitiesLengthQuantity | null;

/**
 * @nullable
 */
export type GeodataMountainResponseDescription = LocaleApiLocaleLocalizedString | null;

/**
 * Element of mountain ranges list
 */
export interface GeodataMountainResponse {
    /** Alternative names */
    alternative_names?: LocaleApiLocaleGeoName[];
    /** @nullable */
    description?: GeodataMountainResponseDescription;
    /** @nullable */
    elevation?: GeodataMountainResponseElevation;
    /** Mountain ID */
    id: number;
    /**
     * Default mountain name
     * @nullable
     */
    object_name?: string | null;
    /** @nullable */
    prominence?: GeodataMountainResponseProminence;
    /** @nullable */
    volcano?: GeodataMountainResponseVolcano;
}

/**
 * @nullable
 */
export type GeodataMountainRangeResponseDescription = LocaleApiLocaleLocalizedString | null;

/**
 * @nullable
 */
export type GeodataMountainRangeResponseArea = LocaleApiQuantitiesAreaQuantity | null;

/**
 * Element of mountain ranges list
 */
export interface GeodataMountainRangeResponse {
    /** Alternative names */
    alternative_names?: LocaleApiLocaleGeoName[];
    /** @nullable */
    area?: GeodataMountainRangeResponseArea;
    /** @nullable */
    description?: GeodataMountainRangeResponseDescription;
    glaciers_area: LocaleApiQuantitiesAreaQuantity;
    /** Glaciers count */
    glaciers_count: number;
    /** Mountain range ID */
    id: number;
    /** Mountain passes count within mountain range */
    mountain_passes_count: number;
    /** Mountains count within mountain range */
    mountains_count: number;
    /**
     * Default object name
     * @nullable
     */
    object_name?: string | null;
    /**
     * Parent ID
     * @nullable
     */
    parent_id?: number | null;
}

/**
 * Filter to apply to mountain ranges list
 */
export interface GeodataMountainRangeListFilter {
    /**
   * Parent object: mountain ranges, countries, etc. If null, filter will not be applied. If empty list, only
toplevel mountain ranges will be returned
   * @nullable
   */
    parent_id?: number[] | null;
}

/**
 * Mountain range scale information
 */
export interface GeodataMountainPassScale {
    /** Maximum known grade */
    max: string;
    /** Minimum known grade */
    min: string;
}

/**
 * @nullable
 */
export type GeodataMountainPassResponseScale = GeodataMountainPassScale | null;

/**
 * @nullable
 */
export type GeodataMountainPassResponseElevation = LocaleApiQuantitiesLengthQuantity | null;

/**
 * @nullable
 */
export type GeodataMountainPassResponseDescription = LocaleApiLocaleLocalizedString | null;

/**
 * Element of mountain ranges list
 */
export interface GeodataMountainPassResponse {
    /** Alternative names */
    alternative_names?: LocaleApiLocaleGeoName[];
    /** @nullable */
    description?: GeodataMountainPassResponseDescription;
    /** @nullable */
    elevation?: GeodataMountainPassResponseElevation;
    /** Mountain pass ID */
    id: number;
    /**
     * Default mountain pass name
     * @nullable
     */
    object_name?: string | null;
    /** @nullable */
    scale?: GeodataMountainPassResponseScale;
}

/**
 * Filter to apply to mountain passes list
 */
export interface GeodataMountainPassListFilter {
    parent_id?: number[];
}

/**
 * Filter to apply to mountains list
 */
export interface GeodataMountainListFilter {
    parent_id?: number[];
}

/**
 * @nullable
 */
export type GeodataGlacierResponseDescription = LocaleApiLocaleLocalizedString | null;

/**
 * @nullable
 */
export type GeodataGlacierResponseArea = LocaleApiQuantitiesAreaQuantity | null;

/**
 * Element of countries list
 */
export interface GeodataGlacierResponse {
    /** Alternative names */
    alternative_names?: LocaleApiLocaleGeoName[];
    /** @nullable */
    area?: GeodataGlacierResponseArea;
    /** @nullable */
    description?: GeodataGlacierResponseDescription;
    /** Glacier ID */
    id: number;
    /** Mountain passes count within glacier */
    mountain_passes_count: number;
    /** Mountains count within glacier */
    mountains_count: number;
    /**
     * Default object name
     * @nullable
     */
    object_name?: string | null;
    /**
     * Parent ID
     * @nullable
     */
    parent_id?: number | null;
}

/**
 * Filter to apply to glaciers list
 */
export interface GeodataGlacierListFilter {
    /** Parent object: mountain ranges, countries, etc. If empty list, filter will not be applied */
    parent_id?: number[];
}

/**
 * @nullable
 */
export type GeodataCountryResponseDescription = LocaleApiLocaleLocalizedString | null;

/**
 * @nullable
 */
export type GeodataCountryResponseArea = LocaleApiQuantitiesAreaQuantity | null;

/**
 * Element of countries list
 */
export interface GeodataCountryResponse {
    /** Alternative names */
    alternative_names?: LocaleApiLocaleGeoName[];
    /** @nullable */
    area?: GeodataCountryResponseArea;
    /** @nullable */
    description?: GeodataCountryResponseDescription;
    glaciers_area: LocaleApiQuantitiesAreaQuantity;
    /** Glaciers count */
    glaciers_count: number;
    /** Country ID */
    id: number;
    /** Mountain passes count within country */
    mountain_passes_count: number;
    /** Mountains count within country */
    mountains_count: number;
    /**
     * Default object name
     * @nullable
     */
    object_name?: string | null;
    /**
     * Parent ID
     * @nullable
     */
    parent_id?: number | null;
}

/**
 * @nullable
 */
export type GeodataCountryRegionResponseDescription = LocaleApiLocaleLocalizedString | null;

/**
 * @nullable
 */
export type GeodataCountryRegionResponseArea = LocaleApiQuantitiesAreaQuantity | null;

/**
 * Element of country regions list
 */
export interface GeodataCountryRegionResponse {
    /** Alternative names */
    alternative_names?: LocaleApiLocaleGeoName[];
    /** @nullable */
    area?: GeodataCountryRegionResponseArea;
    /** @nullable */
    description?: GeodataCountryRegionResponseDescription;
    glaciers_area: LocaleApiQuantitiesAreaQuantity;
    /** Glaciers count */
    glaciers_count: number;
    /** Country region ID */
    id: number;
    /** Mountain passes count within country */
    mountain_passes_count: number;
    /** Mountains count within country */
    mountains_count: number;
    /**
     * Default object name
     * @nullable
     */
    object_name?: string | null;
    /**
     * Parent ID
     * @nullable
     */
    parent_id?: number | null;
}

/**
 * Filter to apply to country regions list
 */
export interface GeodataCountryRegionListFilter {
    /** Parent object: mountain ranges, countries, etc. If empty list, filter will not be applied */
    parent_id?: number[];
}

/**
 * Filter to apply to countries list
 */
export interface GeodataCountryListFilter {
    /** Parent object: mountain ranges, countries, etc. If empty list, filter will not be applied */
    parent_id?: number[];
}

/**
 * Current user information
 */
export interface CurrentUserInfoResponse {
    /** When user was created */
    create_date: string;
    /** Internal user ID */
    id: number;
    /**
     * When authenticated user used API last time
     * @nullable
     */
    last_seen_date?: string | null;
    /** User person */
    person: string;
    /** Username */
    username: string;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Returns current user information
 * @summary Returns current user information
 */
export const currentUserInfo = (options?: SecondParameter<typeof createInstance>) => {
    return createInstance<CurrentUserInfoResponse>(
        { url: `/v1/current_user`, method: 'GET' },
        options,
    );
};

/**
 * Returns list of countries
 * @summary Returns list of countries
 */
export const countriesList = (
    params: CountriesListParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataCountryResponse[]>(
        { url: `/v1/geodata_country`, method: 'GET', params },
        options,
    );
};

/**
 * Returns country information
 * @summary Returns country information
 */
export const country = (
    id: number,
    params?: CountryParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataCountryResponse>(
        { url: `/v1/geodata_country/${id}`, method: 'GET', params },
        options,
    );
};

/**
 * Returns list of countries regions
 * @summary Returns list of countries regions
 */
export const countryRegionsList = (
    params: CountryRegionsListParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataCountryRegionResponse[]>(
        { url: `/v1/geodata_countryregion`, method: 'GET', params },
        options,
    );
};

/**
 * Returns country region information
 * @summary Returns country region information
 */
export const countryRegion = (
    id: number,
    params?: CountryRegionParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataCountryResponse>(
        { url: `/v1/geodata_countryregion/${id}`, method: 'GET', params },
        options,
    );
};

/**
 * Returns list of glaciers
 * @summary Returns list of glaciers
 */
export const glaciersList = (
    params: GlaciersListParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataGlacierResponse[]>(
        { url: `/v1/geodata_glacier`, method: 'GET', params },
        options,
    );
};

/**
 * Returns glacier information
 * @summary Returns glacier information
 */
export const glacier = (
    id: number,
    params?: GlacierParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataGlacierResponse>(
        { url: `/v1/geodata_glacier/${id}`, method: 'GET', params },
        options,
    );
};

/**
 * Returns list of mountains
 * @summary Returns list of mountains
 */
export const mountainsList = (
    params: MountainsListParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataMountainResponse[]>(
        { url: `/v1/geodata_mountain`, method: 'GET', params },
        options,
    );
};

/**
 * Returns mountain information
 * @summary Returns mountain information
 */
export const mountain = (
    id: number,
    params?: MountainParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataMountainResponse>(
        { url: `/v1/geodata_mountain/${id}`, method: 'GET', params },
        options,
    );
};

/**
 * Returns list of mountain passes
 * @summary Returns list of mountain passes
 */
export const mountainPassesList = (
    params: MountainPassesListParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataMountainPassResponse[]>(
        { url: `/v1/geodata_mountainpass`, method: 'GET', params },
        options,
    );
};

/**
 * Returns mountain pass information
 * @summary Returns mountain pass information
 */
export const mountainPass = (
    id: number,
    params?: MountainPassParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataMountainPassResponse>(
        { url: `/v1/geodata_mountainpass/${id}`, method: 'GET', params },
        options,
    );
};

/**
 * Returns list of mountain ranges which belongs to the toplevel or specified mountain range
 * @summary Returns list of mountain ranges which belongs to the toplevel or specified mountain range
 */
export const mountainRangesList = (
    params: MountainRangesListParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataMountainRangeResponse[]>(
        { url: `/v1/geodata_mountainrange`, method: 'GET', params },
        options,
    );
};

/**
 * Returns mountain range information
 * @summary Returns mountain range information
 */
export const mountainRange = (
    id: number,
    params?: MountainRangeParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<GeodataMountainRangeResponse>(
        { url: `/v1/geodata_mountainrange/${id}`, method: 'GET', params },
        options,
    );
};

/**
 * Returns list of users
 * @summary Returns list of users
 */
export const userList = (
    params?: UserListParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<UserListResponse[]>({ url: `/v1/user`, method: 'GET', params }, options);
};

/**
 * Returns user information
 * @summary Returns user information
 */
export const userInfo = (userId: number, options?: SecondParameter<typeof createInstance>) => {
    return createInstance<UserInfoResponse[]>(
        { url: `/v1/user/${userId}`, method: 'GET' },
        options,
    );
};

/**
 * Deletes current session of user
 * @summary Deletes current session of user
 */
export const logout = (options?: SecondParameter<typeof createInstance>) => {
    return createInstance<ReactAdminOKResponse>(
        { url: `/v1/user_logout`, method: 'POST' },
        options,
    );
};

export type CurrentUserInfoResult = NonNullable<Awaited<ReturnType<typeof currentUserInfo>>>;
export type CountriesListResult = NonNullable<Awaited<ReturnType<typeof countriesList>>>;
export type CountryResult = NonNullable<Awaited<ReturnType<typeof country>>>;
export type CountryRegionsListResult = NonNullable<Awaited<ReturnType<typeof countryRegionsList>>>;
export type CountryRegionResult = NonNullable<Awaited<ReturnType<typeof countryRegion>>>;
export type GlaciersListResult = NonNullable<Awaited<ReturnType<typeof glaciersList>>>;
export type GlacierResult = NonNullable<Awaited<ReturnType<typeof glacier>>>;
export type MountainsListResult = NonNullable<Awaited<ReturnType<typeof mountainsList>>>;
export type MountainResult = NonNullable<Awaited<ReturnType<typeof mountain>>>;
export type MountainPassesListResult = NonNullable<Awaited<ReturnType<typeof mountainPassesList>>>;
export type MountainPassResult = NonNullable<Awaited<ReturnType<typeof mountainPass>>>;
export type MountainRangesListResult = NonNullable<Awaited<ReturnType<typeof mountainRangesList>>>;
export type MountainRangeResult = NonNullable<Awaited<ReturnType<typeof mountainRange>>>;
export type UserListResult = NonNullable<Awaited<ReturnType<typeof userList>>>;
export type UserInfoResult = NonNullable<Awaited<ReturnType<typeof userInfo>>>;
export type LogoutResult = NonNullable<Awaited<ReturnType<typeof logout>>>;
